name = "crypto-nextjs-api"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set via wrangler secret put)
# SUPABASE_URL and SUPABASE_ANON_KEY will be set as secrets

[env.production]
name = "crypto-nextjs-api"

[env.staging]
name = "crypto-nextjs-api-staging"